from __future__ import annotations

import uuid as uuid_module
from typing import TYPE_CHECKING

from django.contrib.auth import get_user_model
from django.db import models, transaction

from .enums import OrganizationInvitationStatus, OrganizationRole
from .exceptions import AlreadyActiveMemberError, DuplicateInvitationError

if TYPE_CHECKING:
    from collections.abc import Iterable

    # Imported only for type annotations; a runtime import would create a
    # managers <-> models cycle (models imports the managers below).
    from .models import Organization, OrganizationInvitation, OrganizationMember
    # The project's user model is `custom.CustomUser` (not Django's `User`); annotate as such.
    from custom.models import CustomUser as UserType


# The reserved name of the organization owned by the self-hosted singleton Guest -- the sole account
# under `SUPPRESS_AUTHENTICATION` (a self-hosted single-user run). The name doubles as the lookup key,
# and is shown to that user as their household's name.
_SELF_HOSTED_ORGANIZATION_NAME = 'My Organization'

# Prefix of the auto-provisioned personal-household name (`user-<uuid>`) assigned
# when a user has no organization. It embeds the user's UUID -- deliberately not
# personal data -- and means nothing to a person, so the UI shows a placeholder
# for it (see Organization.display_name).
_AUTOGENERATED_NAME_PREFIX = 'user-'


def is_autogenerated_organization_name( name : str ) -> bool:
    """Whether `name` is an auto-provisioned personal-household name
    (`user-<uuid>`, from `create_default_for_user`), as opposed to one a person
    chose."""
    if not name.startswith( _AUTOGENERATED_NAME_PREFIX ):
        return False
    candidate = name[ len( _AUTOGENERATED_NAME_PREFIX ) : ]
    try:
        uuid_module.UUID( candidate )
    except ValueError:
        return False
    return True


class OrganizationManager( models.Manager ):

    @transaction.atomic
    def create_for_owner( self,
                          user : UserType,
                          name : str       ) -> 'Organization':
        """Create an organization named `name`, owned by `user` as an active
        OWNER.

        Self-contained: the organization and its owner membership are created in
        one transaction, so a partial failure can never leave an ownerless
        organization.
        """
        organization = self.create( name = name )
        organization.members.create(
            user = user,
            organization_role = OrganizationRole.OWNER,
        )
        return organization

    @transaction.atomic
    def create_for_email( self, email : str, name : str ) -> 'Organization':
        """Create a passwordless user for `email` and an organization named
        `name` that they own.

        The user authenticates via magic link (no usable password). The whole
        operation is atomic.
        """
        user = get_user_model().objects.create_user( email = email )
        return self.create_for_owner( user, name )

    def create_default_for_user( self, user : UserType ) -> 'Organization':
        """The organization a user owns by default when they have none, named from their uuid
        (deliberately not personal data such as an email).

        The single home for that naming policy, reusable wherever a user must be auto-provisioned
        an organization -- not encoded by the caller.
        """
        return self.create_for_owner( user, f'{_AUTOGENERATED_NAME_PREFIX}{user.uuid}' )

    def get_or_create_self_hosted_owner( self ) -> UserType:
        """The singleton Guest that owns the reserved self-hosted organization -- the sole account
        under `SUPPRESS_AUTHENTICATION` (a self-hosted single-user run).

        Created on first use (an email-less Guest owning a `My Organization` household) and found
        thereafter by that reserved name. This replaces the former shared, *memberless* organization:
        the self-hosted user is now a real account owning a normal organization, so downstream code
        treats it exactly like any other authenticated user rather than as an anonymous special case.

        Not locked against a concurrent first request: two simultaneous cold starts could each create
        a household, after which the reserved-name lookup settles deterministically on one. Acceptable
        for a single-user deployment, whose requests are effectively serial after the first.
        """
        with transaction.atomic():
            existing = self.filter( name = _SELF_HOSTED_ORGANIZATION_NAME ).first()
            if existing is not None:
                owner = existing.members.filter(
                    organization_role = OrganizationRole.OWNER,
                    is_active = True,
                ).select_related( 'user' ).first()
                return owner.user
            guest = get_user_model().objects.create_guest()
            self.create_for_owner( guest, _SELF_HOSTED_ORGANIZATION_NAME )
            return guest


class OrganizationMemberManager( models.Manager ):

    def for_user( self, user : UserType ) -> models.QuerySet:
        """Active memberships for `user` (the organizations they can access)."""
        return self.filter( user = user, is_active = True )

    def active_membership_for( self,
                               user              : UserType,
                               organization_uuid ) -> 'OrganizationMember | None':
        """The user's active membership of the organization identified by `organization_uuid`,
        or None when they have no such active membership.

        The membership-scoped lookup that request resolution trusts: it both verifies the user
        belongs to the selected organization and loads that organization (via `select_related`),
        so a stale or forged session selection can never resolve to an organization the user has
        left or never joined.
        """
        return self.filter(
            user = user,
            is_active = True,
            organization__uuid = organization_uuid,
        ).select_related( 'organization' ).first()

    def default_organization_for(
            self, user : UserType,
            exclude_uuids : 'Iterable[uuid_module.UUID]' = () ) -> 'Organization | None':
        """The organization a user lands in when the session carries no valid selection, or None
        when they have no (eligible) active membership.

        Policy: prefer an organization the user owns over one they only belong to, breaking ties by
        earliest creation -- a stable, predictable landing that keeps a member out of another
        household by default. Consulted only when nothing is already selected, so switching away
        from this default always wins. `exclude_uuids` drops organizations from consideration (e.g.
        the read-only example org, which a user may belong to but never lands in as a home).
        """
        memberships = self.for_user( user ).select_related( 'organization' )
        if exclude_uuids:
            memberships = memberships.exclude( organization__uuid__in = exclude_uuids )
        memberships = list( memberships )
        if not memberships:
            return None

        def _landing_rank( membership : 'OrganizationMember' ):
            owns_it = ( membership.organization_role == OrganizationRole.OWNER )
            return ( 0 if owns_it else 1, membership.organization.created_datetime )

        preferred = min( memberships, key = _landing_rank )
        return preferred.organization

    def active_owners( self, organization : 'Organization' ) -> models.QuerySet:
        """Active OWNER memberships of `organization`."""
        return self.filter(
            organization = organization,
            organization_role = OrganizationRole.OWNER,
            is_active = True,
        )


class OrganizationInvitationManager( models.Manager ):

    def invite( self,
                organization : 'Organization',
                role         : OrganizationRole,
                invited_by   : UserType,
                email        : str      = None,
                invited_user : UserType = None ) -> 'OrganizationInvitation':
        """Create a WAITING invitation to join `organization` as `role`, sent by
        `invited_by` (required).

        The invitee is identified by `email`, by `invited_user` (e.g. resolved
        from a UUID), or both -- at least one is required. When only `email` is
        given and it maps to an existing user, that user is linked as
        `invited_user` so deduplication is consistent across both dimensions.

        Raises:
          - ValueError if `invited_by` is None, or neither `email` nor
            `invited_user` is given;
          - AlreadyActiveMemberError if the resolved user is already an active
            member of the organization;
          - DuplicateInvitationError if a pending invitation already exists for
            this organization and the same email or user.

        Closed invitations (accepted/declined/revoked) are retained as history
        and do not block re-inviting; a former (inactive) member is re-invitable
        and is reactivated on acceptance.
        """
        if invited_by is None:
            raise ValueError( 'invited_by is required to create an invitation.' )
        if email is not None:
            email = email.strip() or None
        if ( email is None ) and ( invited_user is None ):
            raise ValueError( 'an invitation requires an email address or a user.' )
        if ( invited_user is None ) and ( email is not None ):
            invited_user = get_user_model().objects.filter( email__iexact = email ).first()
        if invited_user is not None:
            is_active_member = bool(
                invited_user.organization_members.filter(
                    organization = organization,
                    is_active = True,
                ).exists()
            )
            if is_active_member:
                raise AlreadyActiveMemberError(
                    'The invited user is already an active member of this organization.'
                )
        if self._pending_exists( organization, email, invited_user ):
            raise DuplicateInvitationError(
                'A pending invitation already exists for this email or user.'
            )
        return self.create(
            organization = organization,
            email_address = email,
            organization_role = role,
            invited_by = invited_by,
            invited_user = invited_user,
        )

    def _pending_exists( self,
                         organization : 'Organization',
                         email        : str,
                         invited_user : UserType        ) -> bool:
        pending = self.filter(
            organization = organization,
            status = OrganizationInvitationStatus.WAITING,
        )
        if ( email is not None ) and pending.filter( email_address__iexact = email ).exists():
            return True
        if ( invited_user is not None ) and pending.filter( invited_user = invited_user ).exists():
            return True
        return False
