# Generated by Django 5.2.15 on 2026-07-14 20:04

import common.labeled_enum
import ucfp.inputs.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningresultrecord",
            name="usage_role",
            field=common.labeled_enum.LabeledEnumField(
                default="saved",
                enum_class=ucfp.inputs.enums.UsageRole,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Usage Role",
            ),
        ),
        migrations.AddIndex(
            model_name="planningresultrecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="planning_pl_organiz_c62fe4_idx",
            ),
        ),
    ]
