# Generated by Django 5.2.15 on 2026-06-29 22:34

import common.labeled_enum
import django.db.models.deletion
import ucfp.planning.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningResultRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                (
                    "feature",
                    common.labeled_enum.LabeledEnumField(
                        default="financial_forecast",
                        enum_class=ucfp.planning.enums.PlanningFeature,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Feature",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_results",
                        to="organization.organization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_results",
                        to="planning.projectionrunrecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
