# Generated by Django 5.2.15 on 2026-06-30 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_planningresultrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningresultrecord",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="planning.projectionrunrecord",
            ),
        ),
    ]
