# Generated by Django 5.2.15 on 2026-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_planningresultrecord_usage_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectionrunrecord",
            name="source_label",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
