# Generated by Django 5.2.15 on 2026-07-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_entryrecord_account"),
        ("planning", "0003_alter_planningresultrecord_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectionrunrecord",
            name="books",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="accounts.booksofaccountrecord",
            ),
        ),
    ]
