# Generated by Django 5.2.15 on 2026-08-13 01:31

import common.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_projectionrunrecord_source_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planningresultrecord",
            name="data",
            field=common.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="projectionrunrecord",
            name="data",
            field=common.encrypted_fields.EncryptedJSONField(default=dict),
        ),
    ]
