# Generated by Django 5.2.15 on 2026-08-19 23:51

import common.encrypted_fields
import common.labeled_enum
import django.db.models.deletion
import ucfp.accounts.enums
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BooksOfAccountRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Label"
                    ),
                ),
            ],
            options={
                "verbose_name": "Books of Account",
                "verbose_name_plural": "Books of Account",
            },
        ),
        migrations.CreateModel(
            name="EntryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "amount",
                    common.encrypted_fields.EncryptedDecimalField(
                        decimal_places=5,
                        exclusive_min=True,
                        max_digits=19,
                        min_value=Decimal("0"),
                        verbose_name="Amount",
                    ),
                ),
                (
                    "entry_direction",
                    common.labeled_enum.LabeledEnumField(
                        default="debit",
                        enum_class=ucfp.accounts.enums.SideType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Entry Direction",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Transaction Date")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="AccountRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "account_type",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.AccountType,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "system_role",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.SystemAccountRole,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="System Role",
                    ),
                ),
                (
                    "asset_class",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.AssetClass,
                        max_length=33,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Asset Class",
                    ),
                ),
                (
                    "is_valuation",
                    models.BooleanField(default=False, verbose_name="Is Valuation"),
                ),
                (
                    "income_tax_class",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.IncomeTaxClass,
                        max_length=36,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Income Tax Class",
                    ),
                ),
                (
                    "expense_tax_class",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.ExpenseTaxClass,
                        max_length=34,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Expense Tax Class",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "handle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        verbose_name="Handle",
                    ),
                ),
                (
                    "owner_handle",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        verbose_name="Owner Handle",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("closed", models.BooleanField(default=False, verbose_name="Closed")),
                (
                    "display_placement",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Display Placement",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.accountrecord",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
    ]
