# Generated by Django 5.2.15 on 2026-06-17 20:50

import common.labeled_enum
import common.models
import django.db.models.deletion
import ucfp.accounts.enums
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "account_type",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.AccountType,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "system_role",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.SystemAccountRole,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="System Role",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "currency",
                    common.labeled_enum.LabeledEnumField(
                        default="usd",
                        enum_class=ucfp.accounts.enums.CurrencyType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Currency",
                    ),
                ),
                ("closed", models.BooleanField(default=False, verbose_name="Closed")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.account",
                        verbose_name="Parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("as_of_date", models.DateField(verbose_name="As Of Date")),
                ("label", models.CharField(max_length=128, verbose_name="Label")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journals",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal",
                "verbose_name_plural": "Journals",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Transaction Date")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "currency",
                    common.labeled_enum.LabeledEnumField(
                        default="usd",
                        enum_class=ucfp.accounts.enums.CurrencyType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.journal",
                        verbose_name="Journal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "amount",
                    common.models.BoundedDecimalField(
                        decimal_places=5,
                        exclusive_min=True,
                        max_digits=19,
                        min_value=Decimal("0"),
                        verbose_name="Amount",
                    ),
                ),
                (
                    "entry_direction",
                    common.labeled_enum.LabeledEnumField(
                        default="debit",
                        enum_class=ucfp.accounts.enums.SideType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Entry Direction",
                    ),
                ),
                (
                    "transaction_amount",
                    common.models.BoundedDecimalField(
                        decimal_places=5,
                        exclusive_min=True,
                        max_digits=19,
                        min_value=Decimal("0"),
                        verbose_name="Transaction Amount",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="accounts.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="accounts.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("organization", "account_type"),
                name="unique_root_account_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_role__isnull", False)),
                fields=("organization", "system_role"),
                name="unique_system_account_role_per_organization",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="entry_amount_strictly_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.CheckConstraint(
                condition=models.Q(("transaction_amount__gt", 0)),
                name="entry_transaction_amount_strictly_positive",
            ),
        ),
    ]
