# Generated by Django 5.2.15 on 2026-06-19 14:54

import common.labeled_enum
import common.models
import django.db.models.deletion
import ucfp.accounts.enums
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksOfAccountRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="Label"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="organization.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Books of Account",
                "verbose_name_plural": "Books of Account",
            },
        ),
        migrations.CreateModel(
            name="AccountRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "account_type",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.AccountType,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Account Type",
                    ),
                ),
                (
                    "system_role",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.SystemAccountRole,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="System Role",
                    ),
                ),
                (
                    "asset_class",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.AssetClass,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Asset Class",
                    ),
                ),
                (
                    "is_valuation",
                    models.BooleanField(default=False, verbose_name="Is Valuation"),
                ),
                (
                    "income_tax_class",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.IncomeTaxClass,
                        max_length=32,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Income Tax Class",
                    ),
                ),
                (
                    "expense_tax_class",
                    common.labeled_enum.NullableLabeledEnumField(
                        blank=True,
                        default=None,
                        enum_class=ucfp.accounts.enums.ExpenseTaxClass,
                        max_length=33,
                        null=True,
                        use_safe_conversion=True,
                        verbose_name="Expense Tax Class",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                ("closed", models.BooleanField(default=False, verbose_name="Closed")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="accounts.accountrecord",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "books",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="accounts.booksofaccountrecord",
                        verbose_name="Books",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.CreateModel(
            name="TransactionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="Transaction Date")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "books",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.booksofaccountrecord",
                        verbose_name="Books",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.CreateModel(
            name="EntryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "amount",
                    common.models.BoundedDecimalField(
                        decimal_places=5,
                        exclusive_min=True,
                        max_digits=19,
                        min_value=Decimal("0"),
                        verbose_name="Amount",
                    ),
                ),
                (
                    "entry_direction",
                    common.labeled_enum.LabeledEnumField(
                        default="debit",
                        enum_class=ucfp.accounts.enums.SideType,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Entry Direction",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="accounts.accountrecord",
                        verbose_name="Account",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="accounts.transactionrecord",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("books", "account_type"),
                name="unique_root_account_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_role__isnull", False)),
                fields=("books", "system_role"),
                name="unique_system_account_role_per_books",
            ),
        ),
        migrations.AddConstraint(
            model_name="entryrecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="entry_amount_strictly_positive",
            ),
        ),
    ]
