# Generated by Django 5.2.15 on 2026-08-13 00:41

import common.encrypted_fields
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="entryrecord",
            name="entry_amount_strictly_positive",
        ),
        migrations.AlterField(
            model_name="entryrecord",
            name="amount",
            field=common.encrypted_fields.EncryptedDecimalField(
                decimal_places=5,
                exclusive_min=True,
                max_digits=19,
                min_value=Decimal("0"),
                verbose_name="Amount",
            ),
        ),
    ]
