# Generated by Django 5.2.15 on 2026-08-19 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booksofaccountrecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="organization.organization",
                verbose_name="Organization",
            ),
        ),
        migrations.AddField(
            model_name="accountrecord",
            name="books",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="accounts.booksofaccountrecord",
                verbose_name="Books",
            ),
        ),
        migrations.AddField(
            model_name="entryrecord",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="accounts.accountrecord",
                verbose_name="Account",
            ),
        ),
        migrations.AddField(
            model_name="transactionrecord",
            name="books",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="accounts.booksofaccountrecord",
                verbose_name="Books",
            ),
        ),
        migrations.AddField(
            model_name="entryrecord",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="accounts.transactionrecord",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("books", "account_type"),
                name="unique_root_account_per_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("system_role__isnull", False)),
                fields=("books", "system_role"),
                name="unique_system_account_role_per_books",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("handle__isnull", False)),
                fields=("books", "handle"),
                name="unique_account_handle_per_books",
            ),
        ),
    ]
