# Generated by Django 5.2.15 on 2026-06-17 22:08

import common.labeled_enum
import ucfp.accounts.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="asset_class",
            field=common.labeled_enum.NullableLabeledEnumField(
                blank=True,
                default=None,
                enum_class=ucfp.accounts.enums.AssetClass,
                max_length=32,
                null=True,
                use_safe_conversion=True,
                verbose_name="Asset Class",
            ),
        ),
    ]
