# Generated by Django 5.2.15 on 2026-06-20 15:54

import common.labeled_enum
import ucfp.accounts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrecord",
            name="handle",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Handle",
            ),
        ),
        migrations.AddField(
            model_name="accountrecord",
            name="owner_handle",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=128,
                null=True,
                verbose_name="Owner Handle",
            ),
        ),
        migrations.AlterField(
            model_name="accountrecord",
            name="expense_tax_class",
            field=common.labeled_enum.NullableLabeledEnumField(
                blank=True,
                default=None,
                enum_class=ucfp.accounts.enums.ExpenseTaxClass,
                max_length=34,
                null=True,
                use_safe_conversion=True,
                verbose_name="Expense Tax Class",
            ),
        ),
        migrations.AlterField(
            model_name="accountrecord",
            name="income_tax_class",
            field=common.labeled_enum.NullableLabeledEnumField(
                blank=True,
                default=None,
                enum_class=ucfp.accounts.enums.IncomeTaxClass,
                max_length=36,
                null=True,
                use_safe_conversion=True,
                verbose_name="Income Tax Class",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("handle__isnull", False)),
                fields=("books", "handle"),
                name="unique_account_handle_per_books",
            ),
        ),
    ]
