# Generated by Django 5.2.15 on 2026-06-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_valuation",
            field=models.BooleanField(default=False, verbose_name="Is Valuation"),
        ),
    ]
