# Generated by Django 5.2.15 on 2026-07-07 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_accountrecord_handle_accountrecord_owner_handle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entryrecord",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="accounts.accountrecord",
                verbose_name="Account",
            ),
        ),
    ]
