# Generated by Django 5.2.15 on 2026-08-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accountrecord",
            name="unique_system_account_role_per_books",
        ),
        migrations.RemoveConstraint(
            model_name="accountrecord",
            name="unique_account_handle_per_books",
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                fields=("books", "system_role"),
                name="unique_system_account_role_per_books",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                fields=("books", "handle"), name="unique_account_handle_per_books"
            ),
        ),
    ]
