# Generated by Django 5.2.15 on 2026-07-07 21:15

import common.labeled_enum
import ucfp.accounts.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_entryrecord_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountrecord",
            name="asset_class",
            field=common.labeled_enum.NullableLabeledEnumField(
                blank=True,
                default=None,
                enum_class=ucfp.accounts.enums.AssetClass,
                max_length=33,
                null=True,
                use_safe_conversion=True,
                verbose_name="Asset Class",
            ),
        ),
    ]
