# Generated by Django 5.2.15 on 2026-08-26 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_unconditional_role_handle_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="accountrecord",
            name="unique_root_account_per_type",
        ),
        migrations.AddField(
            model_name="accountrecord",
            name="root_account_type_key",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(parent__isnull=True, then=models.F("account_type"))
                ),
                output_field=models.CharField(max_length=64),
            ),
        ),
        migrations.AddConstraint(
            model_name="accountrecord",
            constraint=models.UniqueConstraint(
                fields=("books", "root_account_type_key"),
                name="unique_root_account_per_type",
            ),
        ),
    ]
