# Generated by Django 5.2.15 on 2026-06-17 23:12

import common.labeled_enum
import ucfp.accounts.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_is_valuation"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="income_tax_class",
            field=common.labeled_enum.NullableLabeledEnumField(
                blank=True,
                default=None,
                enum_class=ucfp.accounts.enums.IncomeTaxClass,
                max_length=32,
                null=True,
                use_safe_conversion=True,
                verbose_name="Income Tax Class",
            ),
        ),
    ]
