# Generated by Django 5.2.15 on 2026-07-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_accountrecord_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountrecord",
            name="display_placement",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Display Placement"
            ),
        ),
    ]
