# Generated by Django 5.2.15 on 2026-06-17 23:57

import common.labeled_enum
import ucfp.accounts.enums
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_income_tax_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="expense_tax_class",
            field=common.labeled_enum.NullableLabeledEnumField(
                blank=True,
                default=None,
                enum_class=ucfp.accounts.enums.ExpenseTaxClass,
                max_length=33,
                null=True,
                use_safe_conversion=True,
                verbose_name="Expense Tax Class",
            ),
        ),
    ]
