# Generated by Django 5.2.15 on 2026-08-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="pending_email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="pending email address",
            ),
        ),
    ]
