# Generated by Django 5.2.15 on 2026-08-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0002_customuser_pending_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="email_verified",
        ),
    ]
