# Generated by Django 5.2.15 on 2026-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="display_timezone",
            field=models.CharField(
                choices=[
                    ("UTC", "UTC"),
                    ("Pacific/Honolulu", "Pacific/Honolulu"),
                    ("Pacific/Auckland", "Pacific/Auckland"),
                    ("America/Anchorage", "America/Anchorage"),
                    ("America/Vancouver", "America/Vancouver"),
                    ("America/Los_Angeles", "America/Los Angeles"),
                    ("America/Denver", "America/Denver"),
                    ("America/Chicago", "America/Chicago"),
                    ("America/New_York", "America/New York"),
                    ("America/Toronto", "America/Toronto"),
                    ("America/Mexico_City", "America/Mexico City"),
                    ("America/Sao_Paulo", "America/Sao Paulo"),
                    (
                        "America/Argentina/Buenos_Aires",
                        "America/Argentina/Buenos Aires",
                    ),
                    ("Europe/London", "Europe/London"),
                    ("Europe/Paris", "Europe/Paris"),
                    ("Europe/Berlin", "Europe/Berlin"),
                    ("Europe/Athens", "Europe/Athens"),
                    ("Europe/Istanbul", "Europe/Istanbul"),
                    ("Europe/Moscow", "Europe/Moscow"),
                    ("Africa/Cairo", "Africa/Cairo"),
                    ("Africa/Lagos", "Africa/Lagos"),
                    ("Africa/Johannesburg", "Africa/Johannesburg"),
                    ("Asia/Dubai", "Asia/Dubai"),
                    ("Asia/Kolkata", "Asia/Kolkata"),
                    ("Asia/Bangkok", "Asia/Bangkok"),
                    ("Asia/Jakarta", "Asia/Jakarta"),
                    ("Asia/Singapore", "Asia/Singapore"),
                    ("Asia/Hong_Kong", "Asia/Hong Kong"),
                    ("Asia/Shanghai", "Asia/Shanghai"),
                    ("Asia/Seoul", "Asia/Seoul"),
                    ("Asia/Tokyo", "Asia/Tokyo"),
                    ("Australia/Perth", "Australia/Perth"),
                    ("Australia/Sydney", "Australia/Sydney"),
                    ("Australia/Melbourne", "Australia/Melbourne"),
                ],
                default="America/Chicago",
                max_length=64,
                verbose_name="Display Timezone",
            ),
        ),
    ]
