# Generated by Django 5.2.15 on 2026-08-26 23:33

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="organizationinvitation",
            name="unique_pending_invitation_per_org_email",
        ),
        migrations.RemoveConstraint(
            model_name="organizationinvitation",
            name="unique_pending_invitation_per_org_user",
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="pending_email_key",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(
                            ("email_address__isnull", False), ("status", "waiting")
                        ),
                        then=django.db.models.functions.text.Lower("email_address"),
                    )
                ),
                output_field=models.CharField(max_length=254),
            ),
        ),
        migrations.AddField(
            model_name="organizationinvitation",
            name="pending_user_key",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        models.Q(
                            ("invited_user__isnull", False), ("status", "waiting")
                        ),
                        then=models.F("invited_user"),
                    )
                ),
                output_field=models.BigIntegerField(),
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationinvitation",
            constraint=models.UniqueConstraint(
                fields=("organization", "pending_email_key"),
                name="unique_pending_invitation_per_org_email",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizationinvitation",
            constraint=models.UniqueConstraint(
                fields=("organization", "pending_user_key"),
                name="unique_pending_invitation_per_org_user",
            ),
        ),
    ]
