# Generated by Django 5.2.15 on 2026-08-19 23:51

import common.encrypted_fields
import common.labeled_enum
import django.db.models.deletion
import ucfp.inputs.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssumptionsRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                (
                    "acknowledged_sections",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Acknowledged Sections"
                    ),
                ),
                (
                    "usage_role",
                    common.labeled_enum.LabeledEnumField(
                        default="saved",
                        enum_class=ucfp.inputs.enums.UsageRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Usage Role",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assumptions",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlansRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("data", common.encrypted_fields.EncryptedJSONField(default=dict)),
                (
                    "acknowledged_sections",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Acknowledged Sections"
                    ),
                ),
                (
                    "usage_role",
                    common.labeled_enum.LabeledEnumField(
                        default="saved",
                        enum_class=ucfp.inputs.enums.UsageRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Usage Role",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="organization.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("data", common.encrypted_fields.EncryptedJSONField(default=dict)),
                (
                    "acknowledged_sections",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Acknowledged Sections"
                    ),
                ),
                (
                    "usage_role",
                    common.labeled_enum.LabeledEnumField(
                        default="saved",
                        enum_class=ucfp.inputs.enums.UsageRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Usage Role",
                    ),
                ),
                ("effective_date", models.DateField(verbose_name="Effective Date")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profiles",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScenarioRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "usage_role",
                    common.labeled_enum.LabeledEnumField(
                        default="saved",
                        enum_class=ucfp.inputs.enums.UsageRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Usage Role",
                    ),
                ),
                (
                    "assumptions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="inputs.assumptionsrecord",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="organization.organization",
                    ),
                ),
                (
                    "plans",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="inputs.plansrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioExploration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "frame_start_from",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "frame_duration_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "frame_interval",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_exploration",
                        to="organization.organization",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anchored_explorations",
                        to="inputs.scenariorecord",
                    ),
                ),
                (
                    "working",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owning_exploration",
                        to="inputs.scenariorecord",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="assumptionsrecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="inputs_assu_organiz_db21d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plansrecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="inputs_plan_organiz_f95544_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scenariorecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="inputs_scen_organiz_44b197_idx",
            ),
        ),
    ]
