# Generated by Django 5.2.15 on 2026-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assumptionsrecord",
            name="acknowledged_sections",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Acknowledged Sections"
            ),
        ),
        migrations.AddField(
            model_name="plansrecord",
            name="acknowledged_sections",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Acknowledged Sections"
            ),
        ),
        migrations.AddField(
            model_name="profilerecord",
            name="acknowledged_sections",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Acknowledged Sections"
            ),
        ),
    ]
