# Generated by Django 5.2.15 on 2026-07-15 23:46

import common.labeled_enum
import django.db.models.deletion
import ucfp.inputs.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "usage_role",
                    common.labeled_enum.LabeledEnumField(
                        default="saved",
                        enum_class=ucfp.inputs.enums.UsageRole,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Usage Role",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assumptionsrecord",
            name="usage_role",
            field=common.labeled_enum.LabeledEnumField(
                default="saved",
                enum_class=ucfp.inputs.enums.UsageRole,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Usage Role",
            ),
        ),
        migrations.AddField(
            model_name="plansrecord",
            name="usage_role",
            field=common.labeled_enum.LabeledEnumField(
                default="saved",
                enum_class=ucfp.inputs.enums.UsageRole,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Usage Role",
            ),
        ),
        migrations.AddField(
            model_name="profilerecord",
            name="usage_role",
            field=common.labeled_enum.LabeledEnumField(
                default="saved",
                enum_class=ucfp.inputs.enums.UsageRole,
                max_length=32,
                use_safe_conversion=True,
                verbose_name="Usage Role",
            ),
        ),
        migrations.AddIndex(
            model_name="assumptionsrecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="inputs_assu_organiz_db21d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="plansrecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="inputs_plan_organiz_f95544_idx",
            ),
        ),
        migrations.AddField(
            model_name="scenariorecord",
            name="assumptions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="inputs.assumptionsrecord",
            ),
        ),
        migrations.AddField(
            model_name="scenariorecord",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="scenariorecord",
            name="plans",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenarios",
                to="inputs.plansrecord",
            ),
        ),
        migrations.AddIndex(
            model_name="scenariorecord",
            index=models.Index(
                fields=["organization", "usage_role", "updated_datetime"],
                name="inputs_scen_organiz_44b197_idx",
            ),
        ),
    ]
