# Generated by Django 5.2.15 on 2026-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0002_scenariorecord_assumptionsrecord_usage_role_and_more"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="scenariorecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("usage_role", "working")),
                fields=("organization",),
                name="one_working_scenario_per_organization",
            ),
        ),
    ]
