# Generated by Django 5.2.15 on 2026-07-31 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0003_scenariorecord_one_working_scenario_per_organization"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScenarioExploration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="scenariorecord",
            name="one_working_scenario_per_organization",
        ),
        migrations.AddField(
            model_name="scenarioexploration",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scenario_exploration",
                to="organization.organization",
            ),
        ),
        migrations.AddField(
            model_name="scenarioexploration",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anchored_explorations",
                to="inputs.scenariorecord",
            ),
        ),
        migrations.AddField(
            model_name="scenarioexploration",
            name="working",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owning_exploration",
                to="inputs.scenariorecord",
            ),
        ),
    ]
