# Generated by Django 5.2.15 on 2026-08-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0004_scenarioexploration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenarioexploration",
            name="frame_duration_years",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenarioexploration",
            name="frame_interval",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="scenarioexploration",
            name="frame_start_from",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
