# Generated by Django 5.2.15 on 2026-08-13 01:31

import common.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inputs", "0005_scenarioexploration_frame_duration_years_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plansrecord",
            name="data",
            field=common.encrypted_fields.EncryptedJSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="profilerecord",
            name="data",
            field=common.encrypted_fields.EncryptedJSONField(default=dict),
        ),
    ]
