"""`/inputs/` -- the inputs area: the Scenarios landing, the three editable flows, and the section interview.

All served by this app's own views. The interview's section routes keep stable `name`s
(`interview_section`, `residence`, ...) so existing `{% url %}` references resolve unchanged; the
flow is derived from the section, so the section URL needs no flow segment.
"""
from django.urls import path

from . import views

urlpatterns = [
    path( 'scenarios/', views.ScenariosHomeView.as_view(), name = 'scenarios_home' ),
    path( 'scenarios/new/', views.ScenarioNewView.as_view(), name = 'scenario_new' ),
    path( 'scenarios/<uuid:uuid>/resume/', views.ScenarioResumeView.as_view(), name = 'scenario_resume' ),
    path( 'scenarios/<uuid:uuid>/rename/', views.ScenarioRenameView.as_view(), name = 'scenario_rename' ),
    path( 'scenarios/<uuid:uuid>/delete/', views.ScenarioDeleteView.as_view(), name = 'scenario_delete' ),

    # The three input flows, each editable on its own (a scenario build chains Plans then Assumptions).
    path( 'profile/', views.FlowEntryView.as_view( flow = 'profile' ), name = 'flow_profile' ),
    path( 'plans/', views.FlowEntryView.as_view( flow = 'plans' ), name = 'flow_plans' ),
    path( 'plans/new/', views.PlansNewView.as_view(), name = 'plan_new' ),
    path( 'plans/<uuid:uuid>/clone/', views.PlansCloneView.as_view(), name = 'plan_clone' ),
    path( 'plans/<uuid:uuid>/rename/', views.PlansRenameView.as_view(), name = 'plan_rename' ),
    path( 'plans/<uuid:uuid>/delete/', views.PlansDeleteView.as_view(), name = 'plan_delete' ),
    path( 'plans/<uuid:uuid>/', views.PlansSelectView.as_view(), name = 'plan_select' ),
    path( 'assumptions/', views.FlowEntryView.as_view( flow = 'assumptions' ),
          name = 'flow_assumptions' ),
    path( 'assumptions/new/', views.AssumptionsNewView.as_view(), name = 'assumptions_new' ),
    path( 'assumptions/<uuid:uuid>/clone/', views.AssumptionsCloneView.as_view(),
          name = 'assumptions_clone' ),
    path( 'assumptions/<uuid:uuid>/rename/', views.AssumptionsRenameView.as_view(),
          name = 'assumptions_rename' ),
    path( 'assumptions/<uuid:uuid>/delete/', views.AssumptionsDeleteView.as_view(),
          name = 'assumptions_delete' ),
    path( 'assumptions/<uuid:uuid>/', views.AssumptionsSelectView.as_view(),
          name = 'assumptions_select' ),

    # The section-driven interview (entered per flow above) + the per-section editors.
    path( 'interview/<str:section>/', views.InterviewView.as_view(), name = 'interview_section' ),
    path( 'interview/income/table/', views.IncomeTableView.as_view(), name = 'income_table' ),
    path( 'interview/debt/list/', views.DebtsView.as_view(), name = 'debts' ),
    path( 'interview/debt/plan/', views.DebtPlanView.as_view(), name = 'debt_plan' ),
    path( 'interview/debt/cards/', views.CreditCardView.as_view(), name = 'credit_card_plan' ),
    path( 'interview/subjects/edit/', views.SubjectsView.as_view(), name = 'subjects' ),
    path( 'interview/accounts/edit/', views.AccountsView.as_view(), name = 'accounts' ),
    path( 'interview/external-factors/edit/', views.ExternalFactorsView.as_view(),
          name = 'external_factors' ),
    path( 'interview/transaction-costs/edit/', views.TransactionCostsView.as_view(),
          name = 'transaction_costs' ),
    path( 'interview/cash-plan/edit/', views.CashPlanView.as_view(), name = 'cash_plan' ),
    path( 'interview/retirement/edit/', views.RetirementView.as_view(), name = 'retirement' ),
    path( 'interview/retirement/contributions/edit/', views.ContributionsView.as_view(),
          name = 'contributions' ),
    path( 'interview/tax-planning/conversions/edit/', views.ConversionsView.as_view(),
          name = 'conversions' ),
    path( 'interview/properties/residence/', views.ResidenceView.as_view(), name = 'residence' ),
    path( 'interview/properties/possessions/', views.PossessionsView.as_view(),
          name = 'possessions' ),
    path( 'interview/properties/rentals/add/', views.RentalFormView.as_view(), name = 'rental_add' ),
    path( 'interview/properties/rentals/<str:handle>/delete/',
          views.RentalDeleteView.as_view(), name = 'rental_delete' ),
    path( 'interview/properties/rentals/<str:handle>/', views.RentalFormView.as_view(),
          name = 'rental_edit' ),
    path( 'interview/properties/second-homes/add/', views.SecondHomeFormView.as_view(),
          name = 'second_home_add' ),
    path( 'interview/properties/second-homes/<str:handle>/delete/',
          views.SecondHomeDeleteView.as_view(), name = 'second_home_delete' ),
    path( 'interview/properties/second-homes/<str:handle>/', views.SecondHomeFormView.as_view(),
          name = 'second_home_edit' ),
    path( 'interview/home-expenses/edit/', views.PropertyExpensesView.as_view(),
          name = 'property_expenses' ),
    path( 'interview/vehicle-expenses/vehicles/add/', views.VehicleFormView.as_view(),
          name = 'vehicle_add' ),
    path( 'interview/vehicle-expenses/vehicles/<str:handle>/delete/',
          views.VehicleDeleteView.as_view(), name = 'vehicle_delete' ),
    path( 'interview/vehicle-expenses/vehicles/<str:handle>/', views.VehicleFormView.as_view(),
          name = 'vehicle_edit' ),
    path( 'interview/vehicle-expenses/costs/edit/', views.VehicleExpensesView.as_view(),
          name = 'vehicle_expenses' ),
    path( 'interview/living-expenses/edit/', views.RecurringExpensesView.as_view(),
          name = 'recurring_expenses' ),
    path( 'interview/events/add/<str:kind>/', views.EventAddView.as_view(), name = 'event_add' ),
    path( 'interview/events/delete/<int:index>/', views.EventDeleteView.as_view(),
          name = 'event_delete' ),
]
