"""`/inputs/` -- the inputs area: the Scenarios landing, the three editable flows, and the section interview.

All served by this app's own views. The interview's section routes keep stable `name`s
(`interview_section`, `residence`, ...) so existing `{% url %}` references resolve unchanged; the
flow is derived from the section, so the section URL needs no flow segment.
"""
from django.urls import path

from . import views

urlpatterns = [
    path( 'scenarios/', views.ScenariosHomeView.as_view(), name = 'scenarios_home' ),
    path( 'scenarios/compose/', views.ScenarioComposeView.as_view(), name = 'scenario_compose' ),
    path( 'scenarios/<uuid:uuid>/edit/', views.ScenarioEditView.as_view(), name = 'scenario_edit' ),
    path( 'scenarios/<uuid:uuid>/rename/', views.ScenarioRenameView.as_view(), name = 'scenario_rename' ),
    path( 'scenarios/<uuid:uuid>/delete/', views.ScenarioDeleteView.as_view(), name = 'scenario_delete' ),
    path( 'scenarios/<uuid:uuid>/delete-confirm/', views.ScenarioDeleteConfirmView.as_view(),
          name = 'scenario_delete_confirm' ),
    path( 'scenarios/<uuid:uuid>/reconcile/', views.ScenarioReconcileView.as_view(),
          name = 'scenario_reconcile' ),

    # The three input flows, each editable on its own (a scenario build chains Plans then Assumptions).
    path( 'profile/', views.FlowEntryView.as_view( flow = 'profile' ), name = 'flow_profile' ),
    path( 'plans/', views.FlowEntryView.as_view( flow = 'plans' ), name = 'flow_plans' ),
    path( 'plans/<uuid:uuid>/rename/', views.PlansRenameView.as_view(), name = 'plans_rename' ),
    path( 'plans/<uuid:uuid>/edit/', views.PlansEditView.as_view(), name = 'plans_edit' ),
    path( 'plans/<uuid:uuid>/reconcile/', views.PlansReconcileView.as_view(), name = 'plans_reconcile' ),
    path( 'assumptions/', views.FlowEntryView.as_view( flow = 'assumptions' ),
          name = 'flow_assumptions' ),
    path( 'assumptions/<uuid:uuid>/rename/', views.AssumptionsRenameView.as_view(),
          name = 'assumptions_rename' ),
    path( 'assumptions/<uuid:uuid>/edit/', views.AssumptionsEditView.as_view(),
          name = 'assumptions_edit' ),

    # The section-driven interview (entered per flow above) + the per-section editors.
    path( 'interview/<str:section>/', views.InterviewView.as_view(), name = 'interview_section' ),
    path( 'interview/income/table/', views.IncomeTableView.as_view(), name = 'income_table' ),
    path( 'interview/debt/add/', views.DebtFormView.as_view(), name = 'debt_add' ),
    path( 'interview/debt/plan/', views.DebtPlanView.as_view(), name = 'debt_plan' ),
    path( 'interview/debt/cards/', views.CreditCardView.as_view(), name = 'credit_card_plan' ),
    # The per-debt catch-alls follow the fixed debt/* routes above, so `plan`/`cards`/`add` are not read
    # as handles.
    path( 'interview/debt/<str:handle>/delete/', views.DebtDeleteView.as_view(), name = 'debt_delete' ),
    path( 'interview/debt/<str:handle>/', views.DebtFormView.as_view(), name = 'debt_edit' ),
    path( 'interview/subjects/edit/', views.SubjectsView.as_view(), name = 'subjects' ),
    path( 'interview/accounts/edit/', views.AccountsView.as_view(), name = 'accounts' ),
    path( 'interview/external-factors/edit/', views.ExternalFactorsView.as_view(),
          name = 'external_factors' ),
    path( 'interview/transaction-costs/edit/', views.TransactionCostsView.as_view(),
          name = 'transaction_costs' ),
    path( 'interview/net-worth/edit/', views.NetWorthView.as_view(),
          name = 'net_worth' ),
    path( 'interview/cash-plan/edit/', views.CashPlanView.as_view(), name = 'cash_plan' ),
    path( 'interview/retirement/edit/', views.RetirementView.as_view(), name = 'retirement' ),
    path( 'interview/retirement/contributions/edit/', views.ContributionsView.as_view(),
          name = 'contributions' ),
    path( 'interview/tax-planning/conversions/edit/', views.ConversionsView.as_view(),
          name = 'conversions' ),
    path( 'interview/tax-planning/withdrawals/edit/', views.WithdrawalsView.as_view(),
          name = 'withdrawals' ),
    path( 'interview/real-estate/residence/', views.ResidenceView.as_view(), name = 'residence' ),
    path( 'interview/possessions/edit/', views.PossessionsView.as_view(),
          name = 'possessions' ),
    path( 'interview/real-estate/rentals/add/', views.RentalFormView.as_view(), name = 'rental_add' ),
    path( 'interview/real-estate/rentals/<str:handle>/delete/',
          views.RentalDeleteView.as_view(), name = 'rental_delete' ),
    path( 'interview/real-estate/rentals/<str:handle>/', views.RentalFormView.as_view(),
          name = 'rental_edit' ),
    path( 'interview/real-estate/second-homes/add/', views.SecondHomeFormView.as_view(),
          name = 'second_home_add' ),
    path( 'interview/real-estate/second-homes/<str:handle>/delete/',
          views.SecondHomeDeleteView.as_view(), name = 'second_home_delete' ),
    path( 'interview/real-estate/second-homes/<str:handle>/', views.SecondHomeFormView.as_view(),
          name = 'second_home_edit' ),
    path( 'interview/vehicles/add/', views.CurrentVehicleFormView.as_view(),
          name = 'current_vehicle_add' ),
    path( 'interview/vehicles/<str:handle>/delete/',
          views.CurrentVehicleDeleteView.as_view(), name = 'current_vehicle_delete' ),
    path( 'interview/vehicles/<str:handle>/', views.CurrentVehicleFormView.as_view(),
          name = 'current_vehicle_edit' ),
    path( 'interview/home-expenses/edit/', views.PropertyExpensesView.as_view(),
          name = 'property_expenses' ),
    path( 'interview/vehicle-expenses/vehicles/add/', views.VehicleFormView.as_view(),
          name = 'vehicle_add' ),
    path( 'interview/vehicle-expenses/vehicles/<str:handle>/delete/',
          views.VehicleDeleteView.as_view(), name = 'vehicle_delete' ),
    path( 'interview/vehicle-expenses/vehicles/<str:handle>/', views.VehicleFormView.as_view(),
          name = 'vehicle_edit' ),
    path( 'interview/vehicle-expenses/current/<str:handle>/', views.VehicleDispositionView.as_view(),
          name = 'vehicle_disposition_edit' ),
    path( 'interview/vehicle-expenses/leased/<str:handle>/', views.LeasedVehicleDispositionView.as_view(),
          name = 'leased_disposition_edit' ),
    path( 'interview/vehicle-expenses/costs/edit/', views.VehicleExpensesView.as_view(),
          name = 'vehicle_expenses' ),
    path( 'interview/living-expenses/edit/', views.RecurringExpensesView.as_view(),
          name = 'recurring_expenses' ),
    path( 'interview/events/add/<str:kind>/', views.EventAddView.as_view(), name = 'event_add' ),
    path( 'interview/events/edit/<int:index>/', views.EventEditView.as_view(), name = 'event_edit' ),
    path( 'interview/events/delete/<int:index>/', views.EventDeleteView.as_view(),
          name = 'event_delete' ),
]
