# Generated by Django 5.2.15 on 2026-08-19 23:51

import common.labeled_enum
import django.db.models.deletion
import ucfp.parameter_sets.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created"
                    ),
                ),
                (
                    "updated_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                (
                    "kind",
                    common.labeled_enum.LabeledEnumField(
                        default="economic_outlook",
                        enum_class=ucfp.parameter_sets.enums.ParameterSetKind,
                        max_length=32,
                        use_safe_conversion=True,
                        verbose_name="Kind",
                    ),
                ),
                ("seeded_data", models.JSONField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_sets",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "organization", "label"),
                        name="parameter_set_unique_kind_owner_label",
                    )
                ],
            },
        ),
    ]
